name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build binaries
        run: |
          BINARY_NAME="hermes"
          VERSION=${GITHUB_REF#refs/tags/}

          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o "dist/${BINARY_NAME}-${VERSION}-linux-amd64"

          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o "dist/${BINARY_NAME}-${VERSION}-darwin-amd64"
          GOOS=darwin GOARCH=arm64 go build -o "dist/${BINARY_NAME}-${VERSION}-darwin-arm64"

          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o "dist/${BINARY_NAME}-${VERSION}-windows-amd64.exe"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
